wireplumber.components = [
  {
    name = armada/default-sink-rank.lua, type = script/lua
    provides = hooks.armada.default-sink-rank
  }
  {
    type = virtual, provides = policy.armada.default-sink
    wants = [ hooks.armada.default-sink-rank ]
  }
]

wireplumber.profiles = {
  main = {
    policy.armada.default-sink = required
  }
}

monitor.bluez.rules = [
  {
    matches = [
      {
        node.name = "~bluez_output.*"
      }
    ]
    actions = {
      update-props = {
        armada.sink-rank = 5
      }
    }
  }
]

monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.usb-*"
      }
    ]
    actions = {
      update-props = {
        armada.sink-rank = 4
      }
    }
  }
]
