wireplumber.components = [
  {
    name = armada/dp-sink.lua, type = script/lua
    arguments = { card = PocketMICRO2, device = 3, rank = 2 }
    provides = monitor.armada.dp-sink.pocketmicro2
    requires = [ api.file-monitor ]
  }
  {
    type = virtual, provides = policy.armada.dp-sink.pocketmicro2
    wants = [ monitor.armada.dp-sink.pocketmicro2 ]
  }
]

wireplumber.profiles = {
  main = {
    policy.armada.dp-sink.pocketmicro2 = required
  }
}

# Keep the sinks open so the HPH PA does not pop on every idle suspend
monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.*"
        alsa.card_name = "PocketMICRO2"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
      }
    }
  }
  {
    matches = [
      {
        node.name = "~alsa_output.*Headphones*"
        alsa.card_name = "PocketMICRO2"
      }
    ]
    actions = {
      update-props = {
        armada.sink-rank = 3
      }
    }
  }
  {
    matches = [
      {
        node.name = "~alsa_output.*Speaker*"
        alsa.card_name = "PocketMICRO2"
      }
    ]
    actions = {
      update-props = {
        armada.sink-rank = 1
      }
    }
  }
]
