# Keep the sinks open so the HPH PA does not pop on every idle suspend
monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.*"
        alsa.card_name = "PocketMICRO2"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
      }
    }
  }
  {
    matches = [
      {
        node.name = "~alsa_output.*DisplayPort*"
        alsa.card_name = "PocketMICRO2"
      }
    ]
    actions = {
      update-props = {
        audio.format = "S16LE"
      }
    }
  }
]

